var data = {
	'AB': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea central-vestica a tarii.</p><p>Resedinta de judet este Municipiul Alba Iulia,care la ultimul recensamant avea 66.369 locuitori.</p><p>Se invecineaza cu urmatoarele judete:Cluj (N),Mures (N-E),(E),Sibiu (S-E),Valcea (S),Hunedoara (S-V),Arad si Bihor (N-V).</p><p>Are o suprafata de 6.242 km<sup>2</sup>,care reprezinta aproximativ 2.62% din suprafata tarii (locul 16 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 382.999 locuitori (locul 28 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 61.4 loc/km<sup>2</sup>(locul 35 pe tara).</p><p>Municipii:Alba Iulia (66.369 loc.),Aiud (28.881 loc.),Blaj (20.758 loc.) si Sebes (27.68 loc.).</p><p>Orase:Abrud (6.213 loc.),Baia de Aries (4.673 loc.),Campeni (8.096 loc.),Cugir (25.929 loc.),Ocna Mures (15.526 loc.),Teius (7.279 loc.) si Zlatna (8.607 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 49,6% barbati si 50,4% femei</p><p>La ultimul recensamant,220.011 (57.5%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 162.988 (42.5%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (90,4%),aceasta fiind urmata de populatia de etnie maghiara (5,4%),rroma (3,8%).si populatia germana (0,3%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 86% din totalul populatiei. Celelalte religii sunt:romano-catolica (1,3%),greco-catolica (3,6%),reformata (3,8%),penticostala(1,5%),e.t.c.</p>',
		'lat': 46.07667,
		'long': 23.57381
	},
	'AR': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea vestica a tarii.</p><p>Resedinta de judet este Municipiul Arad,care la ultimul recensamant avea 172.824 locuitori. (singurul municipiu din judet)</p><p>Se invecineaza cu:Bihor (N),Alba (N-E),Hunedoara (E),Timis (S) si granita cu Ungaria (V)</p><p>Are o suprafata de 7.754 km<sup>2</sup>,care reprezinta aproximativ 3.25% din suprafata tarii (locul 5 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 461.730 locuitori (locul 20 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 59.5 loc/km<sup>2</sup>(locul 37 pe tara).</p><p>Orase:Chisineu-Cris (8.341 loc.),Curtici (9.726 loc.),Ineu (10.216 loc.),Lipova (11.246 loc.),Nadlac (8.154 loc.),Pancota (7.199 loc.) si Sebis (6.31 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 48,1% barbati si 51,9% femei</p><p>La ultimul recensamant,234.016 (50,6%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 227.714 (49,4%)</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (82,1%),aceasta fiind urmata de populatia de etnie maghiara (10,7%),rroma (3,9%).si populatia germana (1,1%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 72,9% din totalul populatiei. Celelalte religii sunt:romano-catolica (10,1%),greco-catolica (1,1%),reformata (2,7%),penticostala(6,3%),baptista (4%),e.t.c.</p>',
		'lat': 46.18649,
		'long': 21.31240
	},
	'AG': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea sudica a tarii.</p><p>Resedinta de judet este Municipiul Pitesti,care la ultimul recensamant avea 168.756 locuitori.</p><p>Se invecineaza cu urmatoarele judete:Brasov (N-E),Dambovita (E),Teleorman (S),Olt (S-V),Valcea (V),Sibiu (N-V).</p><p>Are o suprafata de 6.862 km<sup>2</sup>,care reprezinta aproximativ 2.88% din suprafata tarii (locul 10 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 653.903 locuitori (locul 9 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 95.3 loc/km<sup>2</sup>(locul 11 pe tara).</p><p>Municipii:Pitesti (168.756 loc.),Campulung (38.285 loc.) si Curtea de Arges (32.626 loc.).</p><p>Orase:Costesti (10.892 loc.),Mioveni (35.849 loc.) si Topoloveni (10.626 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 48,7% barbati si 51,3% femei</p><p>La ultimul recensamant,297.034 (45,4%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 356.869 (54,6%)</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (98,4%),aceasta fiind urmata de populatia de etnie rroma (1,3%)</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 0.98 din totalul populatiei. Celelalte religii sunt:romano-catolica (0,2%),penticostala(0,4%),e.t.c.</p>',
		'lat': 44.85648,
		'long': 24.86918
	},
	'BC': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea estica a tarii.</p><p>Resedinta de judet este Municipiul Bacau,care la ultimul recensamant avea 175.921 locuitori.</p><p>Se invecineaza cu urmatoarele judete:Neamt (N),Vaslui (E),Vrancea (S),Covasna (S-V),Harghita (N-V).</p><p>Are o suprafata de 6.621 km<sup>2</sup>,care reprezinta aproximativ 2.78% din suprafata tarii (locul 14 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 708.751 locuitori (locul 5 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 107 loc/km<sup>2</sup>(locul 7 pe tara).</p><p>Municipii:Bacau (175.921 loc.),Moinesti (24.204 loc.) si Onesti (51.681 loc.).</p><p>Orase:Buhusi (18.980 loc.),Comanesti (23.796 loc.),Darmanesti (14.222 loc.),Slanic Moldova (5.017 loc.) si Targu Ocna (13.598 loc.)</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 49,4% barbati si 50,6% femei</p><p>La ultimul recensamant,327.419 (46,1%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 381.332 (53,9%)</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (97,4%),aceasta fiind urmata de populatia de etnie rroma (1,7%) si maghiara  (0,6%)</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 81,2% din totalul populatiei. Celelalte religii sunt:romano-catolica (17,1%),greco-catolica (0,1%),penticostala(0,6%),e.t.c.</p>',
		'lat': 46.56704,
		'long': 26.91457
	},
	'BH': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea nord-vestica a tarii.</p><p>Resedinta de judet este Municipiul Oradea,care la ultimul recensamant avea 206.527 locuitori.</p><p>Se invecineaza cu:Satu Mare (N),Salaj si Cluj in est,Alba (S-E),Arad (S) si granita cu Ungaria (V).</p><p>Are o suprafata de 7.544 km<sup>2</sup>,care reprezinta aproximativ 3.16% din suprafata tarii (locul 6 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 600.223 locuitori (locul 11 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 79.6 loc/km<sup>2</sup>(locul 23 pe tara).</p><p>Municipii:Oradea (206.527 loc.) si Salonta (18.137 loc.).</p><p>Orase:Alesd (10.376 loc.),Beius (10.985 loc.),Marghita (17.175 loc.),Nucet (2.394 loc.),Stei (8.648 loc.),Valea lui Mihai (10.317 loc.) si Vascau (2.839 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 48,6% barbati si 51,4% femei.</p><p>La ultimul recensamant,287.398 (47,9%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 312.825 (52,1%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (67,4%),aceasta fiind urmata de populatia de etnie maghiara (25,9%),rroma (5%).si populatia germana (0,2%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 59,6% din totalul populatiei. Celelalte religii sunt:romano-catolica (9,3%),greco-catolica (2,3%),reformata (18.1,5%),penticostala(5,7%),e.t.c.</p>',
		'lat': 47.04650,
		'long': 21.91894
	},
	'BN': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea nordica a tarii.</p><p>Resedinta de judet este Municipiul Bistrita,care la ultimul recensamant avea 81.467 locuitori. (singurul municipiu din judet).</p><p>Se invecineaza cu urmatoarele judete:Maramures (N),Suceava (E),Mures (S),Cluj (V).</p><p>Are o suprafata de 5.355 km<sup>2</sup>,care reprezinta aproximativ 2.25% din suprafata tarii (locul 26 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 312.325 locuitori (locul 34 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 58.3 loc/km<sup>2</sup>(locul 38 pe tara).</p><p>Orase:Beclean (10.935 loc.),Nasaud (10.639 loc.) si Sangeorz-Bai (10.224 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 49,5% barbati si 50,5% femei.</p><p>La ultimul recensamant,113.260 (36,2%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 199.065 (63,8%)</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (90,2%),aceasta fiind urmata de populatia de etnie maghiara (5,9%),rroma (3,6%).si populatia germana (0,2%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 82,9% din totalul populatiei. Celelalte religii sunt:romano-catolica (1,2%),greco-catolica (2,3%),reformata (4,6%),penticostala(6,4%),e.t.c.</p>',
		'lat': 47.13926,
		'long': 24.48910
	},
	'BT': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea nord-estica a tarii.</p><p>Resedinta de judet este Municipiul Botosani,care la ultimul recensamant avea 115.344 locuitori.</p><p>Se invecineaza cu urmatoarele judete:Iasi (S),Suceava (V),granita cu Ucraina (N-V) si Republica Moldova (E).</p><p>Are o suprafata de 4.986 km<sup>2</sup>,care reprezinta aproximativ 2.09% din suprafata tarii (locul 29 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 454.023 locuitori (locul 22 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 91.1 loc/km<sup>2</sup>(locul 13 pe tara).</p><p>Municipii:Botosani (115.344 loc.) si Dorohoi (31.073 loc.).</p><p>Orase:Darabani (11.867 loc.) si Saveni (8.177 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 49% barbati si 51% femei.</p><p>La ultimul recensamant,166.461 (36,6%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 287.562 (63,4%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (98,8%),aceasta fiind urmata de populatia de etnie rroma (0,8%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 95,3% din totalul populatiei. Celelalte religii sunt:romano-catolica (0,2%),penticostala(0,2%),e.t.c.</p>',
		'lat': 47.74065,
		'long': 26.66581
	},
	'BV': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea centrala a tarii.</p><p>Resedinta de judet este Municipiul Brasov,care la ultimul recensamant avea 283.901 locuitori.</p><p>Se invecineaza cu urmatoarele judete:Harghita (N),Covasna (E),Buzau (S-E),Prahova,Dambovita si Arges in partea sudica,iar in vest,Sibiu.</p><p>Are o suprafata de 5.363 km<sup>2</sup>,care reprezinta aproximativ 2.25% din suprafata tarii (locul 25 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 373.897 locuitori (locul 29 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 69.7 loc/km<sup>2</sup>(locul 28 pe tara).</p><p>Municipii:Brasov (283.901 loc.),Codlea (24.256 loc.),Fagaras (35.759 loc.) si Sacele (30.044 loc.).</p><p>Orase:Predeal (5.625 loc.),Rasnov (15.436 loc.),Rupea (5.761 loc.),Victoria (9.046 loc.) si Zarnesti (25.332 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 48.8% barbati si 51.2% femei.</p><p>La ultimul recensamant,435.159 (74.0%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 153.207 (26%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (87,1%),aceasta fiind urmata de populatia de etnie maghiara (8,7%),rroma (3,1%).si populatia germana (0,8%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 84,8% din totalul populatiei. Celelalte religii sunt:romano-catolica (4,1%),greco-catolica (0,9%),reformata (2,5%),penticostala(1,.5%),e.t.c.</p>',
		'lat': 45.65798,
		'long': 25.60120
	},
	'BR': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea estica a tarii.</p><p>Resedinta de judet este Municipiul Braila,care la ultimul recensamant avea 216.929 locuitori. (singurul municipiu din judet).</p><p>Se invecineaza cu urmatoarele judete:Galati (N),Tulcea (E),Constanta (S-E),Ialomita (S),Buzau (V),Vrancea (N-V).</p><p>Are o suprafata de 4.766 km<sup>2</sup>,care reprezinta aproximativ 2.00% din suprafata tarii (locul 32 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 588.366 locuitori (locul 12 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 123.5 loc/km<sup>2</sup>(locul 6 pe tara).</p><p>Orase:Faurei (4.091 loc.),Ianca (11.341 loc.) si Insuratei (7.341 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 48.9% barbati si 51.1% femei.</p><p>La ultimul recensamant,239.700 (64.1%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 134.197 (35.9%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (97,2%),aceasta fiind urmata de populatia de etnie rroma (1,6%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 98,1% din totalul populatiei. Celelalte religii sunt:romano-catolica (0,4%),crestina de rit vechi(0,8%),penticostala(0,2%),e.t.c.</p>',
		'lat': 45.26525,
		'long': 27.95947
	},
	'B': {
		'geninfo': '',
		'lat': 44.42677,
		'long': 26.10254
	},
	'BZ': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea sud-estica a tarii.</p><p>Resedinta de judet este Municipiul Buzau,care la ultimul recensamant avea 133.116 locuitori.</p><p>Se invecineaza cu urmatoarele judete:Vrancea (N),Braila (E),Ialomita (S),Prahova (V),Brasov si Covasna in partea de nord-vest.</p><p>Are o suprafata de 6.103 km<sup>2</sup>,care reprezinta aproximativ 2.56% din suprafata tarii (locul 17 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 494.982 locuitori (locul 17 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 81.1 loc/km<sup>2</sup>(locul 19 pe tara).</p><p>Municipii:Buzau (133.116 loc.) si Ramnicu Sarat (38.805 loc.).</p><p>Orase:Nehoiu (11.643 loc.) si Pogoanele (7.788 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 48.8% barbati si 51.2% femei.</p><p>La ultimul recensamant,191.352 (38.7%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 303.630 (61.3%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (97%),aceasta fiind urmata de populatia de etnie rroma (2,9%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 98,9% din totalul populatiei. Celelalte religii sunt:romano-catolica (0,1%),adventista de ziua saptea (0,6%),penticostala(0,1%),e.t.c.</p>',
		'lat': 45.13711,
		'long': 26.81711
	},
	'CS': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea sud-vestica a tarii.</p><p>Resedinta de judet este Municipiul Resita,care la ultimul recensamant avea 83.985 locuitori.</p><p>Se invecineaza cu:Timis (N si N-V),Huneadoara (N-E),Gorj si Mehedinti in partea estica,iar in partea sudica,granita cu Serbia.</p><p>Are o suprafata de 8.514 km<sup>2</sup>,care reprezinta aproximativ 3.57% din suprafata tarii (locul 3 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 333.396 locuitori (locul 31 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 39.2 loc/km<sup>2</sup>(locul 40 pe tara).</p><p>Municipii:Resita (83.985 loc.) si Caransebes (28.294 loc.).</p><p>Orase:Anina (9.172 loc.),Baile Herculane (6.026 loc.),Bocsa (16.927 loc.),Moldova Noua (13.912 loc.),Oravita (12.881 loc.) si Otelu Rosu (11.767 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 48.6% barbati si 51.4% femei.</p><p>La ultimul recensamant,182.964 (54.9%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 150.432 (45.1%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (88,2%),aceasta fiind urmata de populatia de etnie rroma (2,4%),sarbi (1,8%).,germani (1,8%) si maghiari (1,8%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 83,5% din totalul populatiei. Celelalte religii sunt:romano-catolica (7,1%),greco-catolica (0,9%),reformata (0,5%),penticostala(2,9%),baptista (4,3%),e.t.c.</p>',
		'lat': 45.30488,
		'long': 21.88189
	},
	'CL': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea sud-estica a tarii.</p><p>Resedinta de judet este Municipiul Calarasi,care la ultimul recensamant avea 70.046 locuitori.</p><p>Se invecineaza cu:Ialomita (N),Constanta (E),Bulgaria (S),Giurgiu (V),Ilfov (N-V).</p><p>Are o suprafata de 5.088 km<sup>2</sup>,care reprezinta aproximativ 2.13% din suprafata tarii (locul 28 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 324.629 locuitori (locul 33 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 63.8 loc/km<sup>2</sup>(locul 33 pe tara).</p><p>Municipii:Calarasi (70.046 loc.) si Oltenita (27.217 loc.).</p><p>Orase:Budesti (9.709 loc.),Fundulea (6.692 loc.) si Lehliu Gara (6.567 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 49.1% barbati si 50.9% femei.</p><p>La ultimul recensamant,120.231 (37.0%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 204.398 (63%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (94,2%),aceasta fiind urmata de populatia de etnie rroma (5,6%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 98,8% din totalul populatiei. Celelalte religii sunt:romano-catolica (0,1%),adventista de ziua a saptea (0,3%),penticostala(0,4%),e.t.c.</p>',
		'lat': 44.20851,
		'long': 27.31374
	},
	'CJ': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea central-nord-vestica a tarii.</p><p>Resedinta de judet este Municipiul Cluj-Napoca,care la ultimul recensamant avea 318.027 locuitori.</p><p>Se invecineaza cu urmatoarele judete:Salaj (N),Maramures (N-E),Bistrita-Nasaud (E),Mures (S-E),Alba (S) si Bihor (V).</p><p>Are o suprafata de 6.674 km<sup>2</sup>,care reprezinta aproximativ 2.80% din suprafata tarii (locul 12 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 703.269 locuitori (locul 6 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 105.4 loc/km<sup>2</sup>(locul 8 pe tara).</p><p>Municipii:Cluj-Napoca (318.027 loc.),Campia Turzii (26.865 loc.),Dej (38.478 loc.),Gherla (24.031 loc.) si Turda (55.775 loc.)</p><p>Orase:pe langa municipii mai exista doar orasul Huedin (9.485 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 48.4% barbati si 51.6% femei.</p><p>La ultimul recensamant,472.650 (67.2%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 230.619 (32.8%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (79,4%),aceasta fiind urmata de populatia de etnie maghiara (17,4%),rroma (2,9%).si populatia germana (0,1%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 72,1% din totalul populatiei. Celelalte religii sunt:romano-catolica (3,7%),greco-catolica (4,3%),reformata (12,3%),penticostala(2,9%),baptista (1%),e.t.c.</p>',
		'lat': 46.77121,
		'long': 23.62364
	},
	'CT': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea sud-estica a tarii.</p><p>Resedinta de judet este Municipiul Constanta,care la ultimul recensamant avea 310.526 locuitori.</p><p>Se invecineaza cu:Tulcea (N),Marea Neagra (E),Bulgaria (S),Calarasi si Ialomita in partea de est,iar in nord-vest,Braila.</p><p>Are o suprafata de 7.071 km<sup>2</sup>,care reprezinta aproximativ 2.97% din suprafata tarii (locul 8 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 715.172 locuitori (locul 4 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 101.1 loc/km<sup>2</sup>(locul 9 pe tara).</p><p>Municipii:Constanta (310.526 loc.),Mangalia (40.037 loc.) si Medgidia (43.867 loc.).</p><p>Orase:Basarabi (10.888 loc.),Cernavoda (18.961 loc.),Eforie (9.482 loc.),Harsova (10.082 loc.),Navodari (32.4005 loc.),Negru Voda (5.566 loc.),Ovidiu (13.131 loc.) si Techirghiol (7.108 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 49% barbati si 51% femei.</p><p>La ultimul recensamant,502.048 (70.2%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 213.124 (29.8%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (91,2%),aceasta fiind urmata de populatia turca (3,4%),tatara (3,3%).si populatia rroma (0,9%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 90,5% din totalul populatiei. Celelalte religii sunt:romano-catolica (0,8%),greco-catolica (0,1%),musulmana (6,8%),penticostala(0,4%),e.t.c.</p>',
		'lat': 44.15980,
		'long': 28.63481
	},
	'CV': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea central-estica a tarii.</p><p>Resedinta de judet este Municipiul Sfantu Gheorghe,care la ultimul recensamant avea 61.512 locuitori.</p><p>Se invecineaza cu urmatoarele judete:Harghita (N),Bacau (N-E),Vrancea (E),Buzau (S-E) si Brasov in vest si sud-vest.</p><p>Are o suprafata de 3.710 km<sup>2</sup>,care reprezinta aproximativ 1.56% din suprafata tarii (locul 39 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 222.274 locuitori (locul 41 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 59.9 loc/km<sup>2</sup>(locul 36 pe tara).</p><p>Municipii:Sfantu Gheorghe (61.512 loc.) si Tirgu Secuiesc (20.465 loc.).</p><p>Orase:Baraolt (9.614 loc.),Covasna (11.204 loc.) si Intorsura Buzaului (8.905 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 49.1% barbati si 50.9% femei.</p><p>La ultimul recensamant,111.700 (50.3%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 110574 (49.7%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din maghiari (73,8%),aceasta fiind urmata de romani (23,2%),rroma (2,7%).si populatia germana (0,1%).</p><p>Populatia din acest judet este de religie:ortodoxa 22,4%,romano-catolica (36,1%),greco-catolica (0,1%),reformata (33,4%),unitariana (4,4%),penticostala(1,4%),e.t.c.</p>',
		'lat': 45.86094,
		'long': 25.78858
	},
	'DB': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea sudica a tarii.</p><p>Resedinta de judet este Municipiul Targoviste,care la ultimul recensamant avea 89.429 locuitori.</p><p>Se invecineaza cu urmatoarele judete:Brasov (N),Prahova (E),Ilfov (S-E),Giurgiu (S),Teleorman (S-V) si Arges (V).</p><p>Are o suprafata de 4.054 km<sup>2</sup>,care reprezinta aproximativ 1.70% din suprafata tarii (locul 37 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 541.326 locuitori (locul 15 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 133.5 loc/km<sup>2</sup>(locul 5 pe tara).</p><p>Municipii:Targoviste (89.429 loc.) si Moreni (20.931 loc.).</p><p>Orase:Fieni (7.661 loc.),Gaesti (15.547 loc.),Pucioasa (15.227 loc.) si Titu (10.226 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 48.9% barbati si 51.1% femei.</p><p>La ultimul recensamant,159.021 (29.4%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 382305 (70.6%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (96,7%),aceasta fiind urmata de populatia de etnie rroma (3%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 96,9% din totalul populatiei. Celelalte religii sunt:romano-catolica (0,2%),adventista de ziua saptea (0,8%),crestina dupa evanghelie (0,6%),penticostala(0,8%),e.t.c.</p>',
		'lat': 44.91182,
		'long': 25.45583
	},
	'DJ': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea sudica a tarii.</p><p>Resedinta de judet este Municipiul Craiova,care la ultimul recensamant avea 302.622 locuitori.</p><p>Se invecineaza cu urmatoarele judete:Gorj (N),Valcea (N-E),Olt (E),Bulgaria (S) si Mehedinti (V si N-V).</p><p>Are o suprafata de 7.414 km<sup>2</sup>,care reprezinta aproximativ 3.11% din suprafata tarii (locul 7 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 737.823 locuitori (locul 3 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 99.5 loc/km<sup>2</sup>(locul 10 pe tara).</p><p>Municipii:Bailesti (20.081 loc.),Craiova (302.622 loc.) si Calafat (18.895 loc.).</p><p>Orase:Filiasi (18.848 loc.) si Segarcea (8.075 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 48.6% barbati si 51.4% femei.</p><p>La ultimul recensamant,368.516 (49.9%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 366.307 (50.1%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (95,5%),aceasta fiind urmata de populatia de etnie rroma (4,3%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 98,4% din totalul populatiei. Celelalte religii sunt:romano-catolica (0,2%),adventista de ziua saptea (0,5%),crestina dupa evanghelie (0,7%),penticostala(0,3%),e.t.c.</p>',
		'lat': 44.33018,
		'long': 23.79488
	},
	'GL': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea estica a tarii.</p><p>Resedinta de judet este Municipiul Galati,care la ultimul recensamant avea 298.584 locuitori.</p><p>Se invecineaza cu urmatoarele judete:Vaslui (N),Rep. Moldova (E),Tulcea (S-E),Braila (S) si Vrancea (V).</p><p>Are o suprafata de 4.466 km<sup>2</sup>,care reprezinta aproximativ 1.87% din suprafata tarii (locul 34 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 619.522 locuitori (locul 10 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 138.7 loc/km<sup>2</sup>(locul 4 pe tara).</p><p>Municipii:Galati (298.584 loc.) si Tecuci (42.012 loc.).</p><p>Orase:Beresti (3.607 loc.) si Targu Bujor (7.617 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 49.5% barbati si 50.5% femei.</p><p>La ultimul recensamant,351.820 (56.8%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 267.702 (43.2%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (97,6%),aceasta fiind urmata de populatia de etnie rroma (2,1%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 98,1% din totalul populatiei. Celelalte religii sunt:romano-catolica (0,4%),adventista de ziua saptea (0,2%),baptista (0,2%),penticostala(0,6%),e.t.c.</p>',
		'lat': 45.43532,
		'long': 28.00799
	},
	'GR': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea sudica a tarii.</p><p>Resedinta de judet este Municipiul Giurgiu,care la ultimul recensamant avea 69.587 locuitori. (singurul municipiu din judet).</p><p>Se invecineaza cu:Dambovita (N),Ilfov (N-E) Calarasi (E),Bulgaria (S) si  Teleorman (V).</p><p>Are o suprafata de 3.526 km<sup>2</sup>,care reprezinta aproximativ 1.48% din suprafata tarii (locul 40 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 298.022 locuitori (locul 37 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 84.5 loc/km<sup>2</sup>(locul 17 pe tara).</p><p>Orase:Bolintin-Vale (11.686 loc.) si Mihailesti (7.483 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 48.8% barbati si 51.2% femei.</p><p>La ultimul recensamant,88.756 (29.8%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 209.266 (70.2%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (96%),aceasta fiind urmata de populatia de etnie rroma (3,9%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 98,5% din totalul populatiei. Celelalte religii sunt:romano-catolica (0,2%),adventista de ziua saptea (0,5%),baptista (0,1%),penticostala(0,1%),e.t.c.</p><p></p>',
		'lat': 43.90371,
		'long': 25.96993
	},
	'GJ': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea sud-vestica a tarii.</p><p>Resedinta de judet este Municipiul Targu Jiu,care la ultimul recensamant avea 96.562 locuitori.</p><p>Se invecineaza cu urmatoarele judete:Hunedoara (N),Valcea (E),Dolj (S),Mehedinti (V) si Caras-Severin (N-V).</p><p>Are o suprafata de 5.602 km<sup>2</sup>,care reprezinta aproximativ 2.35% din suprafata tarii (locul 21 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 387.407 locuitori (locul 27 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 69.2 loc/km<sup>2</sup>(locul 29 pe tara).</p><p>Municipii:Targu Jiu (96.562 loc.) si Motru (22.848 loc.).</p><p>Orase:Bumbesti-Jiu (10.596 loc.),Novaci (6.113 loc.),Rovinari (12.497 loc.),Ticleni (5.273 loc.) si Tirgu Carbunesti (8.731 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 49.4% barbati si 50.6% femei.</p><p>La ultimul recensamant,162.620 (42.0%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 224.787 (58%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (98,3%),aceasta fiind urmata de populatia de etnie rroma (1,5%)  si populatia maghiara (0,2%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 98,5% din totalul populatiei. Celelalte religii sunt:romano-catolica (0,2%),adventista de ziua saptea (0,2%),baptista (0,2%),penticostala(0,6%),e.t.c.</p>',
		'lat': 45.03143,
		'long': 23.26894
	},
	'HR': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea central-estica a tarii.</p><p>Resedinta de judet este Municipiul Miercurea Ciuc,care la ultimul recensamant avea 41.852 locuitori.</p><p>Se invecineaza cu urmatoarele judete:Suceava (N),Neamt (N-E),Bacau (S-E),Covasna (S),Brasov (S-V) si Mures (V).</p><p>Are o suprafata de 6.639 km<sup>2</sup>,care reprezinta aproximativ 2.78% din suprafata tarii (locul 13 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 326.020 locuitori (locul 32 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 49.1 loc/km<sup>2</sup>(locul 39 pe tara).</p><p>Municipii:Miercurea Ciuc (41.852 loc.) Gheorgheni (20.018 loc.),Toplita (15.885 loc.),si Odorheiu Secuiesc (36.926 loc.).</p><p>Orase:Baile Tusnad (1.728 loc.),Balan (7.902 loc.),Borsec (2.864 loc.),Cristuru Secuiesc (9.672 loc.) si Vlahita (7.043 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 49.7% barbati si 50.3% femei.</p><p>La ultimul recensamant,143.885 (44.1%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 182.135 (55.9%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din maghiari (84,6%),aceasta fiind urmata de romani (14,1%) si rroma (1,2%).</p><p>Populatia din acest judet este de religie:ortodoxa 13,3% din totalul populatiei. Celelalte religii sunt:romano-catolica (65,3%),greco-catolica (0,2%),reformata (12,7%),unitariana (7,1%),penticostala(0,1%),e.t.c.</p>',
		'lat': 46.36956,
		'long': 25.79537
	},
	'HD': {
		'geninfo': '<h2>Informatii generale</h2><p>Judetul Hunedoara este asezat pe cursul mijlociu al rauluiMures,in vecinatatea Muntilor Apuseni (N), Orastiei si sureanu(S-E), Retezat-Godeanu, Valcan si Parang (S) si Poiana Rusca(S-V). Cele mai importante rauri care il traverseaza sunt Mures,Strei, Raul Mare, Crisul Alb,si Jiu. Depresiunile intinse ale Hategului si Zarandului se afla pe teritoriul judetului.</p><p>Judetul Hunedoara este bogat in resurse minerale. Aici se extrag minereuri auro-argentifere,carbuni (in special huila,in Valea Jiului). Alte industrii bine reprezentate sunt cea constructoare de masini,chimica,a energiei electrice,de mobila,a materialelor de constructie. Tot aici se gasesc statiunile cu ape termale de la Geoagiu si Calan.</p><p>Judetul Hunedoara se intinde pe o suprafata de 7.063 km<sup>2</sup> (2,9% din teritoriul Romaniei) si are o populatie de 511.300 locuitori (aproximativ 2,5% din populatia tarii).</p>',
		'lat': 45.86626,
		'long': 22.91437
	},
	'IL': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea sud-estica a tarii.</p><p>Resedinta de judet este Municipiul Slobozia,care la ultimul recensamant avea 52.677 locuitori.</p><p>Se invecineaza cu urmatoarele judete:Buzau si Braila in nord,Constanta (E),Calarasi (S),Ilfov (S-V) si Prahova (N-V).</p><p>Are o suprafata de 4.453 km<sup>2</sup>,care reprezinta aproximativ 1.87% din suprafata tarii (locul 35 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 296.486 locuitori (locul 38 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 66.6 loc/km<sup>2</sup>(locul 31 pe tara).</p><p>Municipii:Slobozia (52.677 loc.),Fetesti (33.197 loc.) si Urziceni (17.089 loc.).</p><p>Orase:Fierbinti Targ (5.253 loc.) si Tandarei (12.515 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 49.4% barbati si 50.6% femei.</p><p>La ultimul recensamant,115.478 (38.9%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 181.008 (61.1%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (95,6%),aceasta fiind urmata de populatia de etnie rroma (4,1%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 98,5% din totalul populatiei. Celelalte religii sunt:romano-catolica (0,1%),adventista de ziua saptea (0,4%),penticostala(0,5%),e.t.c.</p>',
		'lat': 44.56289,
		'long': 27.36137
	},
	'IS': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea nord-estica a tarii.</p><p>Resedinta de judet este Municipiul Iasi,care la ultimul recensamant avea 321.58 locuitori.</p><p>Se invecineaza cu:Botosani (N),Rep. Moldova (E),Vaslui (S),Neamt (V) si Suceava (N-V).</p><p>Are o suprafata de 5.476 km<sup>2</sup>,care reprezinta aproximativ 2.30% din suprafata tarii (locul 23 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 819.044 locuitori (locul 2 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 149.6 loc/km<sup>2</sup>(locul 3 pe tara).</p><p>Municipii:Iasi (321.58 loc.) si Pascani (42.172 loc.).</p><p>Orase:Harlau (11.271 loc.) si Targu Frumos (13..619 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 49.2% barbati si 50.8% femei.</p><p>La ultimul recensamant,388.642 (47.5%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 430.402 (52.5%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (98,1%),aceasta fiind urmata de populatia de etnie rroma (1,2%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 92,9% din totalul populatiei. Celelalte religii sunt:romano-catolica (4,7%),greco-catolica (0,1%),adventista de ziua saptea (0,3%),penticostala(0,5%),e.t.c.</p>',
		'lat': 47.15845,
		'long': 27.60144
	},
	'IF': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea sudica a tarii.</p><p>Resedinta de judet este Municipiul Bucuresti,care la ultimul recensamant avea 1.921.751 locuitori.</p><p>Se invecineaza cu urmatoarele judete:Prahova (N),Ialomita (N-E),Calarasi (S-E),Giurgiu (S-V) si Dambovita (N-V).</p><p>Are o suprafata de 1.583 km<sup>2</sup>,care reprezinta aproximativ 0.66% din suprafata tarii (locul 41 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 300.109 locuitori (locul 36 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 189.6 loc/km<sup>2</sup>(locul 1 pe tara).</p><p>Orase:Buftea (20.328 loc.),Bragadiru (8.184 loc.),Chitila (12.65 loc.),Magurele (9.274 loc.),Otopeni (10.225 loc.),Pantelimon (16.031 loc.),Popesti-Leordeni (15.114 loc.) si Voluntari (29.995 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 49.3% barbati si 50.7% femei.</p><p>La ultimul recensamant,30.548 (10.2%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 269.561 (89.8%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (96%),aceasta fiind urmata de populatia de etnie rroma (3,7%)  si populatia maghiara (0,1%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 96,5% din totalul populatiei. Celelalte religii sunt:romano-catolica (2,1%),greco-catolica (0,1%),adventista de ziua saptea (0,3%),penticostala(0,3%),e.t.c.</p>',
		'lat': 44.42677,
		'long': 26.10254
	},
	'MM': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea nordica a tarii.</p><p>Resedinta de judet este Municipiul Baia Mare,care la ultimul recensamant avea 137.976 locuitori.</p><p>Se invecineaza cu:Ucraina (N),Suceava (E),Bistrita-Nasaud (S-E),Cluj (S),Salaj (S-V) si Satu Mare (V).</p><p>Are o suprafata de 6.304 km<sup>2</sup>,care reprezinta aproximativ 2.64% din suprafata tarii (locul 15 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 510.688 locuitori (locul 16 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 81.0 loc/km<sup>2</sup>(locul 20 pe tara).</p><p>Municipii:Baia Mare (137.976 loc.) si Sighetu Marmatiei (41.246 loc.).</p><p>Orase:Baia Sprie (16.246 loc.),Borsa (27.032 loc.),Cavnic (5.216 loc.),Seini (10.129 loc.),Targu Lapus (13.365 loc.) si Viseu de Sus (16.887 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 49.2% barbati si 50.8% femei.</p><p>La ultimul recensamant,268.472 (52.6%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 242.216 (47.4%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (82%),aceasta fiind urmata de populatia de etnie maghiara (9,1%),ucraineni (6,7%).rromi (1,7%) si germani (0,4%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 77,8% din totalul populatiei. Celelalte religii sunt:romano-catolica (6,1%),greco-catolica (5,6%),reformata (4,1%),penticostala(3,1%),adventista de ziua a saptea (0,7%),baptista (0,5),e.t.c.</p>',
		'lat': 47.65674,
		'long': 23.58499
	},
	'MH': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea sud-vestica a tarii.</p><p>Resedinta de judet este Municipiul Drobeta-Turnu Severin,care la ultimul recensamant avea 104.035 locuitori.</p><p>Se invecineaza cu urmatoarele judete:Gorj (N),Dolj (E),Bulgaria si Serbia (S) si Caras-Severin (V).</p><p>Are o suprafata de 4.933 km<sup>2</sup>,care reprezinta aproximativ 2.07% din suprafata tarii (locul 30 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 306.118 locuitori (locul 35 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 62.1 loc/km<sup>2</sup>(locul 34 pe tara).</p><p>Municipii:Drobeta-Turnu Severin (104.035 loc.) si Orsova (12.967 loc.).</p><p>Orase:Baia de Arama (5.617 loc.),Strehaia (11.741 loc.) si Vanju Mare (6.937 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 49.1% barbati si 50.9% femei.</p><p>La ultimul recensamant,141.297 (46.2%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 164.821 (53.8%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (96,1%),aceasta fiind urmata de populatia de etnie rroma (3%)  si populatia sarba (0,4%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 97,6% din totalul populatiei. Celelalte religii sunt:romano-catolica (0,6%),adventista de ziua saptea (0,1%),baptista (0,5%),penticostala(0,5%),e.t.c.</p>',
		'lat': 44.63692,
		'long': 22.65973
	},
	'MS': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea centrala a tarii.</p><p>Resedinta de judet este Municipiul Targu Mures,care la ultimul recensamant avea 149.577 locuitori.</p><p>Se invecineaza cu urmatoarele judete:Bistrita-Nasaud (N),Suceava (N-E),Harghita (E),Brasov (S-E),Sibiu (S),Alba (S-V) si Cluj (N-V).</p><p>Are o suprafata de 6.714 km<sup>2</sup>,care reprezinta aproximativ 2.82% din suprafata tarii (locul 11 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 579.862 locuitori (locul 13 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 86.4 loc/km<sup>2</sup>(locul 15 pe tara).</p><p>Municipii:Targu Mures (149.577 loc.),Reghin (36.023 loc.),Sighisoara (32.287 loc.) si Tarnaveni (26.537 loc.).</p><p>Orase:Iernut (9.445 loc.),Ludus (17.407 loc.) si Sovata (11.568 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 48.9% barbati si 51.1% femei.</p><p>La ultimul recensamant,282.839 (48.8%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 297.023 (51.2%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (53,2%),aceasta fiind urmata de populatia de etnie maghiara (39,3%),rroma (7%).si populatia germana (0,3%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 53,1% din totalul populatiei. Celelalte religii sunt:romano-catolica (9,5%),greco-catolica (2,3%),reformata (26,9%),penticostala(1,2%),unitariana (2,5),adventista de ziua a saptea (1,5%),e.t.c.</p>',
		'lat': 46.53859,
		'long': 24.55144
	},
	'NT': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea nord-estica a tarii.</p><p>Resedinta de judet este Municipiul Piatra Neamt,care la ultimul recensamant avea 105.499 locuitori.</p><p>Se invecineaza cu urmatoarele judete:Suceava (N),Iasi (E),Vaslui (S-E),Bacau (S) si Harghita (V).</p><p>Are o suprafata de 5.896 km<sup>2</sup>,care reprezinta aproximativ 2.47% din suprafata tarii (locul 18 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 557.084 locuitori (locul 14 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 94.5 loc/km<sup>2</sup>(locul 12 pe tara).</p><p>Municipii:Piatra Neamt (105.499 loc.) si Roman (69.483 loc.).</p><p>Orase:Bicaz (8.418 loc.),Roznov (9.265 loc.) si Targu Neamt (20.654 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 49.2% barbati si 50.8% femei.</p><p>La ultimul recensamant,204.054 (36.6%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 353.030 (63.4%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (98,6%),aceasta fiind urmata de populatia de etnie rroma (1,1%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 86,4% din totalul populatiei. Celelalte religii sunt:romano-catolica (11,2%),greco-catolica (0,1%),baptista (0,1%),penticostala(0,3%),e.t.c.</p>',
		'lat': 46.92996,
		'long': 26.37798
	},
	'OT': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea sudica a tarii.</p><p>Resedinta de judet este Municipiul Slatina,care la ultimul recensamant avea 79.171 locuitori.</p><p>Se invecineaza cu urmatoarele judete:Arges (N-E),Teleorman (S-E),Bulgaria (S),Dolj (V) si Valcea (N-V).</p><p>Are o suprafata de 5.498 km<sup>2</sup>,care reprezinta aproximativ 2.31% din suprafata tarii (locul 22 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 490.276 locuitori (locul 18 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 89.2 loc/km<sup>2</sup>(locul 14 pe tara).</p><p>Municipii:Caracal (34.603 loc.) si Slatina (79.171 loc.).</p><p>Orase:Bals (21.194 loc.),Corabia (20.457 loc.),Draganesti-Olt (12.223 loc.),Piatra-Olt (6.395 loc.) si Scornicesti (12.802 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 49.2% barbati si 50.8% femei.</p><p>La ultimul recensamant,186.840 (38.1%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 303436 (61.9%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (98,1%),aceasta fiind urmata de populatia de etnie rroma (1,9%),rroma (%).si populatia germana (%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 99,3% din totalul populatiei. Celelalte religii sunt:romano-catolica (0,1%),adventista de ziua saptea (0,3%),baptista (0,1%),penticostala(0,1%),e.t.c.</p>',
		'lat': 44.43017,
		'long': 24.37169
	},
	'PH': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea sudica a tarii.</p><p>Resedinta de judet este Municipiul Ploiesti,care la ultimul recensamant avea 232.452 locuitori.</p><p>Se invecineaza cu urmatoarele judete:Brasov (N),Buzau (E),Ilfov (S-E),Giurgiu (S),Teleorman (S-V) si Arges (V).</p><p>Are o suprafata de 4.716 km<sup>2</sup>,care reprezinta aproximativ 1.98% din suprafata tarii (locul 33 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 829.224 locuitori (locul 1 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 175.8 loc/km<sup>2</sup>(locul 2 pe tara).</p><p>Municipii:Campina (38.758 loc.) si Ploiesti (232.452 loc.).</p><p>Orase:Azuga (5.213 loc.),Boldesti-Scaeni (11.485 loc.),Baicoi (19.979 loc.),Breaza (18.199 loc.),Busteni (10.374 loc.),Comarnic (13.372 loc.),Mizil (15.755 loc.),Plopeni (9.611 loc.),Sinaia (12.525 loc.),Slanic (7.115 loc.),Urlati (11.876 loc.) si Valenii de Munte (13.296 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 48.6% barbati si 51.4% femei.</p><p>La ultimul recensamant,420.005 (50.7%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 409.219 (49.3%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (97,7%),aceasta fiind urmata de populatia de etnie rroma (2%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 97,2% din totalul populatiei. Celelalte religii sunt:romano-catolica (0,3%),greco-catolica (0,1%),adventista de ziua saptea (0,7%),penticostala(0,6%),e.t.c.</p>',
		'lat': 44.93666,
		'long': 26.01286
	},
	'SM': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea nord-vestica a tarii.</p><p>Resedinta de judet este Municipiul Satu Mare,care la ultimul recensamant avea 115.63 locuitori.</p><p>Se invecineaza cu:Ucraina (N),Maramures (E),Salaj (S),Bihor (S-V) si Ungaria (V si N-V).</p><p>Are o suprafata de 4.418 km<sup>2</sup>,care reprezinta aproximativ 1.85% din suprafata tarii (locul 36 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 369.096 locuitori (locul 30 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 83.5 loc/km<sup>2</sup>(locul 18 pe tara).</p><p>Municipii:Carei (23.268 loc.) si Satu Mare (115.63 loc.).</p><p>Orase:Negresti.Oas (13.956 loc.),Tasnad (9.649 loc.),Ardud (6.515 loc.) si Livada (7.005 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 48.5% barbati si 51.5% femei.</p><p>La ultimul recensamant,162.503 (44.0%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 206.593 (56%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (58,8%),aceasta fiind urmata de populatia de etnie maghiara (35,2%),rroma (3,7%).si populatia germana (1,7%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 50,5% din totalul populatiei. Celelalte religii sunt:romano-catolica (18,1%),greco-catolica (7,9%),reformata (18,7%),penticostala(2,4%),baptista (0,5%),e.t.c.</p>',
		'lat': 47.80167,
		'long': 22.85759
	},
	'SJ': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea nord-vestica a tarii.</p><p>Resedinta de judet este Municipiul Zalau,care la ultimul recensamant avea 63.305 locuitori. (singurul municipiu din judet).</p><p>Se invecineaza cu urmatoarele judete:Maramures (N),Cluj (S si S-E),Bihor (V) si Satu Mare (N-V).</p><p>Are o suprafata de 3.864 km<sup>2</sup>,care reprezinta aproximativ 1.62% din suprafata tarii (locul 38 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 248.407 locuitori (locul 40 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 64.3 loc/km<sup>2</sup>(locul 32 pe tara).</p><p>Orase:Cehu Silvaniei (8.039 loc.),Jibou (11.277 loc.) si Simleu Silvaniei (16.036 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 48.9% barbati si 51.1% femei.</p><p>La ultimul recensamant,98.657 (39.7%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 149.750 (60.3%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (71,2%),aceasta fiind urmata de populatia de etnie maghiara (23,1%) si rroma (5,1%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 66,4% din totalul populatiei. Celelalte religii sunt:romano-catolica (2,6%),greco-catolica (2,8%),reformata (19,5%),penticostala(3,5%),baptista (3,3%),e.t.c.</p>',
		'lat': 47.18546,
		'long': 23.05733
	},
	'SB': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea centrala a tarii.</p><p>Resedinta de judet este Municipiul Sibiu,care la ultimul recensamant avea 155.045 locuitori.</p><p>Se invecineaza cu urmatoarele judete:Mures (N),Brasov (E),Arges (S-E),Valcea (S) si Alba (V).</p><p>Are o suprafata de 5.432 km<sup>2</sup>,care reprezinta aproximativ 2.28% din suprafata tarii (locul 24 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 422.224 locuitori (locul 24 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 77.7 loc/km<sup>2</sup>(locul 25 pe tara).</p><p>Municipii:Medias (55.203 loc.) si Sibiu (155.045 loc.).</p><p>Orase:Agnita (10.866 loc.),Avrig (14.259 loc.),Cisnadie (15.615 loc.),Copsa Mica (5.374 loc.),Dumbraveni (8.411 loc.),Ocna Sibiului (4.116 loc.),Talmaciu (8.828 loc.),Saliste (5.781 loc.) si Miercurea Sibiului (4.066 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 48.6% barbati si 51.4% femei.</p><p>La ultimul recensamant,277.717 (65.8%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 144.507 (34.2%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (90,4%),aceasta fiind urmata de populatia de etnie maghiara (3,7%),rroma (4,2%).si populatia germana (1,6%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 88,9% din totalul populatiei. Celelalte religii sunt:romano-catolica (1,5%),greco-catolica (2,3%),reformata (2,1%),penticostala(1,1%),baptista (0,9%),adventista de ziua saptea (0,4%),e.t.c.</p>',
		'lat': 45.79833,
		'long': 24.12558
	},
	'SV': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea nordica a tarii.</p><p>Resedinta de judet este Municipiul Suceava,care la ultimul recensamant avea 106.138 locuitori.</p><p>Se invecineaza cu:Ucraina (N),Botosani (E),Iasi (S-E),Neamt si Harghita in sud,Mures (S-V),Bistrita-Nasaud (V) si Maramures (N-V).</p><p>Are o suprafata de 8.553 km<sup>2</sup>,care reprezinta aproximativ 3.59% din suprafata tarii (locul 2 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 690.941 locuitori (locul 7 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 80.8 loc/km<sup>2</sup>(locul 21 pe tara).</p><p>Municipii:Campulung Moldovenesc (20.899 loc.),Falticeni (29.899 loc.),Radauti (27.759 loc.),Suceava (106.138 loc.) si Vatra Dornei (16.465 loc.).</p><p>Orase:Brosteni (6.617 loc.),Cajvana (7.279 loc.),Dolhasca (11.091 loc.),Frasin (6.558 loc.),Gura Humorului (15.837 loc.),Liteni (9.892 loc.),Milisauti (8.449 loc.),Salcea (8.707 loc.),Siret (9.371 loc.),Solca (4.462 loc.) si Vicovu de Sus (14.161 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 49% barbati si 51% femei.</p><p>La ultimul recensamant,230.084 (33.3%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 460.857 (66.7%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (96,3%),aceasta fiind urmata de populatia de etnie rroma (1,4%),ucraineana (1,2%).si populatia rusa (0,4%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 88,1% din totalul populatiei. Celelalte religii sunt:romano-catolica (1,2%),greco-catolica (0,2%),baptista (0,5%),penticostala(6,4%),e.t.c.</p>',
		'lat': 47.66345,
		'long': 26.27323
	},
	'TR': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea nordica a tarii.</p><p>Resedinta de judet este Municipiul Suceava,care la ultimul recensamant avea 106.138 locuitori.</p><p>Se invecineaza cu:Ucraina (N),Botosani (E),Iasi (S-E),Neamt si Harghita in sud,Mures (S-V),Bistrita-Nasaud (V) si Maramures (N-V).</p><p>Are o suprafata de 8.553 km<sup>2</sup>,care reprezinta aproximativ 3.59% din suprafata tarii (locul 2 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 690.941 locuitori (locul 7 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 80.8 loc/km<sup>2</sup>(locul 21 pe tara).</p><p>Municipii:Campulung Moldovenesc (20.899 loc.),Falticeni (29.899 loc.),Radauti (27.759 loc.),Suceava (106.138 loc.) si Vatra Dornei (16.465 loc.).</p><p>Orase:Brosteni (6.617 loc.),Cajvana (7.279 loc.),Dolhasca (11.091 loc.),Frasin (6.558 loc.),Gura Humorului (15.837 loc.),Liteni (9.892 loc.),Milisauti (8.449 loc.),Salcea (8.707 loc.),Siret (9.371 loc.),Solca (4.462 loc.) si Vicovu de Sus (14.161 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 49% barbati si 51% femei.</p><p>La ultimul recensamant,230.084 (33.3%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 460.857 (66.7%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (96,3%),aceasta fiind urmata de populatia de etnie rroma (1,4%),ucraineana (1,2%).si populatia rusa (0,4%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 88,1% din totalul populatiei. Celelalte religii sunt:romano-catolica (1,2%),greco-catolica (0,2%),baptista (0,5%),penticostala(6,4%),e.t.c.</p>',
		'lat': 43.97506,
		'long': 25.32826
	},
	'TM': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea vestica a tarii.</p><p>Resedinta de judet este Municipiul Timisoara,care la ultimul recensamant avea 317.651 locuitori.</p><p>Se invecineaza cu urmatoarele judete:Arad (N),Hunedoara (E),Caras-Severin (S),Serbia (V si S-V) si Ungaria (N-V).</p><p>Are o suprafata de 8.697 km<sup>2</sup>,care reprezinta aproximativ 3.65% din suprafata tarii (locul 1 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 677.744 locuitori (locul 8 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 77.9 loc/km<sup>2</sup>(locul 24 pe tara).</p><p>Municipii:Lugoj (44.571 loc.) si Timisoara (317.651 loc.).</p><p>Orase:Buzias (7.714 loc.),Ciacova (7.282 loc.),Deta (6.418 loc.),Faget (7.201 loc.),Gataia (8.087 loc.),Jimbolia (11.113 loc.),Recas (8.599 loc.) si Sannicolau Mare (12.938 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 48.% barbati si 52% femei</p><p>La ultimul recensamant,407.606 (60.1%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 270.138 (39.9%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (83,3%),aceasta fiind urmata de populatia de etnie maghiara (7,6%),rroma (2,4%).,populatia germana (2,1%),sarba (2%) si ucraineana (1,1%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 78,8% din totalul populatiei. Celelalte religii sunt:romano-catolica (10,5%),greco-catolica (1,4%),reformata (1,9%),penticostala(4,2%),baptista (1,5),e.t.c.</p>',
		'lat': 45.74887,
		'long': 21.20868
	},
	'TL': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea sud-estica a tarii.</p><p>Resedinta de judet este Municipiul Tulcea,care la ultimul recensamant avea 92.762 locuitori. (singurul municipiu din judet).</p><p>Se invecineaza cu:Ucraina (N),Marea Neagra (E),Constanta (S),Braila (V) si Galati (N-V).</p><p>Are o suprafata de 8.499 km<sup>2</sup>,care reprezinta aproximativ 3.57% din suprafata tarii (locul 4 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 258.639 locuitori (locul 39 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 30.4 loc/km<sup>2</sup>(locul 41 pe tara).</p><p>Orase:Babadag (10.136 loc.),Isaccea (5.427 loc.),Macin (10.607 loc.) si Sulina (4.607 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 50.1% barbati si 49.9% femei.</p><p>La ultimul recensamant,123.556 (47.8%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 135.083 (52.2%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (89,9%),aceasta fiind urmata de populatia de etnie lipoveana (6,4%),turca (1,3%).si populatia tatara (0,1%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 92,1% din totalul populatiei. Celelalte religii sunt:romano-catolica (0,3%),musulmana (1,5%),crestina de rit vechi(5,4%),penticostala(0,1%),e.t.c.</p><p></p>',
		'lat': 45.17162,
		'long': 28.79144
	},
	'VS': {
		'geninfo': '<h2>Informatii generale</h2><p>Judetul Vaslui este un judet situat în partea de est a tarii,în regiunea istorica Moldova, Romania.</p><p>Este principala poarta de est a Romaniei.</p><p>Judetul face parte din Euroregiunea Siret-Prut-Nistru din 2002.</p><p>Resedinta de judet este municipiul Vaslui.</p>',
		'lat': 46.64069,
		'long': 27.72765
	},
	'VL': {
		'geninfo': '<h2>Informatii generale</h2><p>Este asezat in partea sudica a tarii.</p><p>Resedinta de judet este Municipiul Ramnicu Valcea,care la ultimul recensamant avea 107.656 locuitori.</p><p>Se invecineaza cu urmatoarele judete:Sibiu (N),Arges (E),Olt (S si S-E),Dolj (S-V),Gorj (V),Hunedoara si Alba in partea de nord-vest.</p><p>Are o suprafata de 5.765 km<sup>2</sup>,care reprezinta aproximativ 2.42% din suprafata tarii (locul 20 pe tara).</p><p>La ultimul recensamant al populatiei,acest judet avea aproximativ 413.570 locuitori (locul 25 pe tara).</p><p>Densitatea populatiei in anul 2002,era de 71.7 loc/km<sup>2</sup>(locul 27 pe tara).</p><p>Municipii:Dragasani (20.783 loc.) si Ramnicu Valcea (107.656 loc.).</p><p>Orase:Baile Govora (2.891 loc.),Baile Olanesti (4.608 loc.),Babeni (9.518 loc.),Balcesti (5.785 loc.),Berbesti (5.707 loc.),Brezoi (6.828 loc.),Calimanesti (8.598 loc.),Horezu (6.813 loc.) si Ocnele Mari (3.578 loc.).</p><p>Structura populatiei pe sexe arata un echilibru intre populatia masculina si cea feminina. In anul 2002 locuitorii judetului erau 48.8% barbati si 51.2% femei.</p><p>La ultimul recensamant,161.755 (39.1%) de oameni locuiau in mediul urban in timp ce in mediul rural locuiau 251.815 (60.9%).</p><p>Din punct de vedere al etniei,in acest judet majoritatea populatiei este formata din romani (98,8%),aceasta fiind urmata de populatia de etnie rroma (0,9%)  si populatia maghiara (0,1%).</p><p>Majoritatea populatiei din acest judet este de religie ortodoxa,care reprezinta 99,1% din totalul populatiei. Celelalte religii sunt:romano-catolica (0,2%),adventista de ziua saptea (0,3%),baptista (0,1%),penticostala(0,1%),e.t.c.</p>',
		'lat': 45.09968,
		'long': 24.36932
	},
	'VN': {
		'geninfo': '<h2>Informatii generale</h2><p>Vrancea este judet în regiunile istorice Moldova (la nord de raul Milcov) si Muntenia (la sud de raul Milcov) din Romania. Judetul are o suprafata de 4.863 km<sup>2</sup>,iar resedinta este municipiul Focsani.</p><p>Principalele cursuri de apa: Siret (între Adjud si Namoloasa), Susita, Putna, Milcov, Ramnicu Sarat (de la Ciorasti pana la varsarea sa în Siret).</p><p>Cele mai mari altitudinea detin varfurile Lacaut (1776 m) si Goru (1784 m).</p><p>Populatia Vrancei la diferite recensaminte: 1930:262.560 loc.; 1948:290.183 loc.; 1956:326.532 loc.; 1966:351.292 loc.; 1972:379.660 loc.</p><p>Judete vecine:la nord-est judetul Vaslui,la est judetul Galati,la sud-est judetul Braila,la sud judetul Buzau,la vest judetul Covasna,la nord judetul Bacau.</p>',
		'lat': 45.69647,
		'long': 27.18404
	}
}